spring:
  datasource:
    url: jdbc:h2:~/aicoding
    username: sa
    password:

  h2:
    console:
      enable: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug